[tool.poetry]
name = "hackathon-pip"
version = "0.1.0"
description = ""
authors = ["Nicola Gutierrez <nicolagutierrez.ng@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
